### ISSUE TITLE
Does not start properly

### ISSUE THREAD

**Issue by szsyzx** [xdsai/twitter-monitor#1]
root@instance-20220525-0117:~/twitter-monitor# python3 monitor-single.py
INFO:root:Config successfully loaded
INFO:root:Started monitoring syzxes
Traceback (most recent call last):
  File "monitor-single.py", line 56, in <module>
    tl = api.user_timeline(screen_name = tmp["monitored_user"], count = 1, include_rts = False, tweet_mode = 'extended')[0]._json        #initial timeline pull
  File "/usr/local/lib/python3.8/dist-packages/tweepy/api.py", line 33, in wrapper
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tweepy/api.py", line 46, in wrapper
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tweepy/api.py", line 571, in user_timeline
    return self.request(
  File "/usr/local/lib/python3.8/dist-packages/tweepy/api.py", line 259, in request
    raise Forbidden(resp)
tweepy.errors.Forbidden: 403 Forbidden
453 - You currently have Essential access which includes access to Twitter API v2 endpoints only. If you need access to this endpoint, you’ll need to apply for Elevated access via the Developer Portal. You can learn more here: https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api#v2-access-leve
root@instance-20220525-0117:~/twitter-monitor#

**Comment by xdsai** [comment]
That is pretty self explanatory, the API endpoint you're using isn't the right one, as you need Elevated privileges. Fiddle around in the twitter developer portal, this isn't an issue of the monitor.
